<?php
bolt_decrypt( __FILE__ , 'DOVGzR'); return 0;
##!!!##BgZqXWlhb2xdX2EcQF1wXV5db2FYT2FhYGFubzcGBnFvYRw9bGxYSWtgYWhvWE9lcGFIa2NrNwZxb2EcRWhocWllal1wYVhAXXBdXl1vYVhPYWFgYW43BgZfaF1vbxxPZXBhSGtja09hYWBhbhxhdHBhamBvHE9hYWBhbgZ3BhwcHBwrJiYGHBwcHBwmHE5xahxwZGEcYF1wXV5db2Ecb2FhYG8qBhwcHBwcJisGHBwcHGxxXmhlXxxicWpfcGVrahxucWokJTYccmtlYAYcHBwcdwYcHBwcHBwcHE9lcGFIa2NrNjZfbmFdcGEkJTcGHBwcHHkGeQY=