<?php
bolt_decrypt( __FILE__ , 'gG1Tfd'); return 0;
##!!!##BwdrXmpicG1eYGIdSmxhcmlicFk+cnFlWVBib3NmYGJwOAcHcnBiHUpsYXJpYnBZPnJxZVlAbGtxb15gcXBZU2JvZmN2UnBibzgHcnBiHUpsYXJpYnBZPnJxZVlRb15mcXBZUEpQU2JvZmNmXl9pYjgHB2BpXnBwHVBKUFNib2ZjdlBib3NmYGIdZmptaWJqYmtxcB1TYm9mY3ZScGJvB3gHHR0dHXJwYh1QSlBTYm9mY2ZeX2liOAd6Bw==